source /usr/share/vim/vim??/vimrc_example.vim

set background=dark

set backupdir=~/tmp//

set undofile
set undodir=~/tmp//

set tabstop=4
set shiftwidth=4
set expandtab

set number
set relativenumber

set cursorline

nnoremap <Tab> :tabnext<Enter>
nnoremap <S-Tab> :tabprevious<Enter>

nnoremap <F12> :nohlsearch<Enter>

colorscheme industry

call plug#begin()

" The NERDTree is a file system explorer for the Vim editor.
" Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Fugitive is the premier Vim plugin for Git.
Plug 'tpope/vim-fugitive'

" Tagbar: a class outline viewer for Vim
Plug 'preservim/tagbar', { 'on': 'TagbarToggle' }

" Asynchronous Lint Engine
Plug 'dense-analysis/ale'

" The React syntax highlighting and indenting plugin for vim. Also supports the typescript tsx file.
" Plug 'MaxMEllon/vim-jsx-pretty'

" JavaScript bundle for vim, this bundle provides syntax highlighting and improved indentation.
" Plug 'pangloss/vim-javascript'

" Zeavim allows to use the offline documentation browser Zeal from Vim.
" Plug 'KabbAmine/zeavim.vim'

call plug#end()
