set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.

" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" A tree explorer plugin for vim.
Plugin 'scrooloose/nerdtree'

" A light and configurable statusline/tabline plugin for Vim
Plugin 'itchyny/lightline.vim'
"set laststatus=2

" Check syntax in Vim asynchronously and fix files, with Language Server Protocol (LSP) support
"Plugin 'w0rp/ale'

" A Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks and partial hunks.
Plugin 'airblade/vim-gitgutter'

" surround.vim: quoting/parenthesizing made simple
" http://www.vim.org/scripts/script.php…
"Plugin 'tpope/vim-surround'

" commentary.vim: comment stuff out
" http://www.vim.org/scripts/script.php…
Plugin 'tpope/vim-commentary'

" Vim plugin that displays tags in a window, ordered by scope
" http://majutsushi.github.io/tagbar/
Plugin 'majutsushi/tagbar'

" All of your Plugins must be added before the following line
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'

" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"Plugin 'ascenator/L9', {'name': 'newL9'}

call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set background=dark

set tabstop=4
set shiftwidth=4
set expandtab

set backupdir-=.

set incsearch
"map <F12> :nohl<Enter>
